# 指定 Alacritty 启动时使用 Fish Shell
# [shell]
#   program = "/usr/bin/elvish"

# 不指定 TERM 会导致一些旧机器通过 ssh 连接时无法正常工作
[env]
  TERM = "xterm-256color"

[window]
    opacity = 0.85
    blur = true
    # decorations = "None"
    startup_mode = "Maximized"
    # decorations: None
[font]
    normal = { family = "Source Code Pro", style = "Regular" }
    size = 19

[terminal]
    shell = "/usr/bin/elvish"

# 鼠标配置
[mouse]
  # 点击配置
  #
  # 双击和三击的判定等待时间，数值越小，需要快速的双击才能判定为双击操作
  # double_click: { threshold: 300 }
  # triple_click: { threshold: 300 }

  # 打字的时候临时隐藏鼠标
  hide_when_typing = true
