#! /bin/sh

# monitor
# xrandr --output DP-2 --mode 3840x2160 --rate 160 --primary
# xrandr --output DP-4 --mode 2560x1440 --rate 144 --left-of DP-2

# xorg dpms config
xset dpms 0 0 0

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc wm -O DP-2 DP-4
# bspc monitor DP-2 -d Editor Terminal Terminal2
# bspc monitor DP-4 -d Browser QQ 6 7 8
bspc monitor -d Editor Terminal Terminal2 Browser 5 6 7 8

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.53
bspc config single_monocle       true

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme          longest_side
bspc config initial_polarity          second_child
bspc config removal_adjustment        true

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config pointer_motion_interval   7
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^4'
bspc rule -a flameshot state=floating focus=off
bspc rule -a pavucontrol state=floating

# polybar
"$HOME"/.config/polybar/launch_polybar.sh

wmname LG3D

# Launch picom
exec picom --config "${HOME}"/.config/bspwm/config/picom/picom.conf &

exec fcitx5 & # 输入法
exec dunst -conf "$HOME"/.config/bspwm/config/dunst/dunstrc & # 通知程序
exec nm-applet &
exec flameshot & # 截图工具
exec udiskie --tray &

feh --bg-max "$HOME"/.config/bspwm/assest/background.jpg
# "$HOME"/.config/bspwm/scripts/AutoStaticWall &
# "$HOME"/.config/bspwm/scripts/AutoWall &
