#! /bin/sh

# monitor
xrandr --output DP-2 --mode 3840x2160 --rate 160 --primary
xrandr --output DP-4 --mode 2560x1440 --rate 144 --left-of DP-2

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O DP-2 DP-4
bspc monitor DP-2 -d Editor Terminal Terminal2
bspc monitor DP-4 -d Browser QQ 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^4'
bspc rule -a flameshot state=floating focus=off

# polybar
~/.config/polybar/launch_polybar.sh

wmname LG3D

exec picom &
exec fcitx5 & # 输入法
exec dunst -conf $HOME/.config/dunst/dunstrc & # 通知程序
exec flameshot & # 截图程序
exec browserpass & # 启动浏览器 pass

#/home/lizqwer/scripts/dwm/background.sh &
